export const exploreData = [
   {
      img: "/property-images/card/jakarta.jpg",
      location: "Jakarta",
   },
   {
      img: "/property-images/card/bali.jpg",
      location: "Bali",
   },
   {
      img: "/property-images/card/bandung.jpg",
      location: "Bandung",
   },
   {
      img: "/property-images/card/semarang.jpg",
      location: "Semarang",
   },
   {
      img: "/property-images/card/surabaya.jpg",
      location: "Surabaya",
   },
   {
      img: "/property-images/card/yogyakarta.jpg",
      location: "Yogyakarta",
   },
   {
      img: "/property-images/card/malang.jpg",
      location: "Malang",
   },
   {
      img: "/property-images/card/medan.jpg",
      location: "Medan",
   },
];

export const bannerData = [
   {
      id: "1",
      img: "/property-images/banner/villa-1.jpg",
      propertyName: "The Paradiso",
      location: "Jakarta",
      description: "Your perfect getaway awaits",
      rating: 8.0,
      reviewsCount: 300,
      ratingWord: "Very Good",
      capacity: 2,
      price: 350000,
   },
   {
      id: "2",
      img: "/property-images/banner/villa-2.jpg",
      propertyName: "Coast Heaven",
      location: "Bali",
      description: "Luxury villa on the coast of Bali`s beach",
      rating: 8.8,
      reviewsCount: 170,
      ratingWord: "Fabulous",
      capacity: 3,
      price: 700000,
   },
   {
      id: "3",
      img: "/property-images/banner/villa-3.jpg",
      propertyName: "Imperial",
      location: "Bandung",
      description: "Grand hotel",
      rating: null,
      reviewsCount: null,
      ratingWord: null,
      capacity: 4,
      price: 550000,
   },
   {
      id: "4",
      img: "/property-images/banner/villa-4.jpg",
      propertyName: "The Home",
      location: "Yogyakarta",
      description: "Beautiful villa",
      rating: 7.5,
      reviewsCount: 125,
      ratingWord: "Good",
      capacity: 2,
      price: 250000,
   },
   {
      id: "5",
      img: "/property-images/banner/villa-5.jpg",
      propertyName: "D-lux",
      location: "Surabaya",
      description: "Where you find the perfect place to relax",
      rating: 10.0,
      reviewsCount: 1000,
      ratingWord: "Excelent",
      capacity: 3,
      price: 370000,
   },
   {
      id: "6",
      img: "/property-images/banner/villa-6.jpg",
      propertyName: "Hidden Gem",
      location: "Malang",
      description: "Extraordinary villa with perfect services",
      rating: 9.5,
      reviewsCount: 3125,
      ratingWord: "Exceptional",
      capacity: 2,
      price: 380000,
   },
];
